# This file is generated by the Terraform code of this Solution Guide.
# We recommend that you modify this file only through the Terraform deployment.
export PROJECT=learnings-421714
export REGION=us-central1
export SUBNETWORK=regions/us-central1/subnetworks/default-subnet
export TEMP_LOCATION=gs://$PROJECT/tmp
export SERVICE_ACCOUNT=dataflow-service-account@learnings-421714.iam.gserviceaccount.com

export BQ_DATASET=iot
export BQ_TABLE=maintenance_analytics

export SUBSCRIPTION=projects/learnings-421714/subscriptions/messages-sub

export BIGTABLE_INSTANCE=projects/learnings-421714/instances/iot-analytics
export BIGTABLE_TABLE=$BQ_TABLE
export BT_LOOKUP_KEY=bigtable-lookup-key
