steps:
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      docker build -t ${_TAG} .
substitutions:
    _TAG: unset
options:
    substitutionOption: 'ALLOW_LOOSE'
    automapSubstitutions: true
    # machineType: E2_STANDARD_8
images:
  - ${_TAG}