/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation("junit:junit:4.13.2")
    implementation("com.google.guava:guava:31.1-jre")
    implementation("com.google.cloud.dataflow:google-cloud-dataflow-java-sdk-all:2.5.0")
    implementation("org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.57.0")
    implementation("org.apache.beam:beam-sdks-java-core:2.57.0")
    implementation("org.apache.beam:beam-runners-google-cloud-dataflow-java:2.57.0")
    implementation("org.apache.beam:beam-runners-direct-java:2.57.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(22))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("clickstream_analytics_java.App")
}
