#  Copyright 2026 The synthetic-llm-dataflow-bigquery Authors
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
"""Packaging entry point for the Dataflow Solution Guides build.

The golden source is a uv workspace (`pyproject.toml` + `uv.lock`); this
file packages its two runtime distributions, `sdfb_core` and `sdfb_beam`,
as one setuptools project so `python setup.py sdist` and Dataflow's
`--setup_file` work. Dependencies come from `requirements.txt`, which the
sync generates from `uv.lock`.
"""

import json
import re

from setuptools import find_packages, setup

_SOURCES = {
    "sdfb_core": "packages/sdfb-core/src/sdfb_core",
    "sdfb_beam": "packages/sdfb-beam/src/sdfb_beam",
}


def _requirements(path="requirements.txt"):
  with open(path, encoding="utf-8") as f:
    return [
        line.strip()
        for line in f
        if line.strip() and not line.startswith(("#", "-e", "."))
    ]


def _version():
  """The synced golden-source tag (`.sync-source.json`), else 0.0.0."""
  try:
    with open(".sync-source.json", encoding="utf-8") as f:
      ref = json.load(f).get("ref", "")
  except OSError:
    return "0.0.0"
  return ref[1:] if re.fullmatch(r"v\d+\.\d+\.\d+", ref) else "0.0.0"


def _packages():
  found = []
  for name, directory in _SOURCES.items():
    found.append(name)
    found += [f"{name}.{sub}" for sub in find_packages(where=directory)]
  return found


setup(
    name="dataflow-solution-synthetic-llm-dataflow-bigquery",
    version=_version(),
    description=("Synthetic BigQuery data generated by self-hosted LLMs on "
                 "Dataflow GPU workers."),
    packages=_packages(),
    package_dir=_SOURCES,
    include_package_data=True,
    install_requires=_requirements(),
    python_requires=">=3.11,<3.13",
)
