#!/usr/bin/env bash
#  Copyright 2026 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# Submits the gaming analytics streaming pipeline to Dataflow.
#
# Source the Terraform generated environment first:
#   source scripts/00_set_environment.sh

set -euo pipefail

for var in PROJECT REGION TEMP_LOCATION SERVICE_ACCOUNT INPUT_SUBSCRIPTION OUTPUT_TOPIC \
  ERROR_TOPIC BIGTABLE_INSTANCE BIGTABLE_TABLE BQ_TABLE; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: \$$var is not set. Run 'source scripts/00_set_environment.sh' first." >&2
    exit 1
  fi
done

# MODEL_URI is not produced by Terraform: it points at the scikit-learn pickle
# that scripts/train_model.py uploads to GCS. There is no built-in fallback
# scorer any more, so the pipeline cannot start without it.
if [ -z "${MODEL_URI:-}" ]; then
  echo "ERROR: \$MODEL_URI is not set. Train and upload the model first:" >&2
  echo "         python3 scripts/train_model.py --model_uri=gs://\$BUCKET/models/gaming_recommender.pkl" >&2
  echo "       then: export MODEL_URI=gs://\$BUCKET/models/gaming_recommender.pkl" >&2
  exit 1
fi

# The Dataflow workers must never get a public IP, so they need a subnet with
# Private Google Access. SUBNETWORK is the current variable; NETWORK is kept as
# a fallback for environments generated by older versions of the Terraform code.
SUBNET_OPT=""
if [ -n "${SUBNETWORK:-}" ]; then
  SUBNET_OPT="--subnetwork=${SUBNETWORK}"
elif [ -n "${NETWORK:-}" ]; then
  SUBNET_OPT="--subnetwork=${NETWORK}"
fi

# WORKER_MACHINE_TYPE overrides the machine type exported by Terraform. The
# model runs on the worker CPU, in the Python SDK harness, so a GPU machine
# type would buy nothing; note that Runner v2 multi-language jobs run a Java
# and a Python harness side by side, so give the workers enough memory.
MACHINE_TYPE_OPT=""
EFFECTIVE_MACHINE_TYPE="${WORKER_MACHINE_TYPE:-${MACHINE_TYPE:-}}"
if [ -n "${EFFECTIVE_MACHINE_TYPE}" ]; then
  MACHINE_TYPE_OPT="--workerMachineType=${EFFECTIVE_MACHINE_TYPE}"
fi

DISK_OPT=""
if [ -n "${DISK_SIZE_GB:-}" ]; then
  DISK_OPT="--diskSizeGb=${DISK_SIZE_GB}"
fi

MAX_WORKERS_OPT=""
if [ -n "${MAX_DATAFLOW_WORKERS:-}" ]; then
  MAX_WORKERS_OPT="--maxNumWorkers=${MAX_DATAFLOW_WORKERS}"
fi

./gradlew run -Pargs="
  --runner=DataflowRunner \
  --project=$PROJECT \
  --region=$REGION \
  --tempLocation=$TEMP_LOCATION \
  --serviceAccount=$SERVICE_ACCOUNT \
  $SUBNET_OPT \
  $MACHINE_TYPE_OPT \
  $DISK_OPT \
  $MAX_WORKERS_OPT \
  --streaming \
  --enableStreamingEngine \
  --experiments=use_runner_v2 \
  --usePublicIps=false \
  --inputSubscription=$INPUT_SUBSCRIPTION \
  --outputTopic=$OUTPUT_TOPIC \
  --errorTopic=$ERROR_TOPIC \
  --bigtableInstance=$BIGTABLE_INSTANCE \
  --bigtableTable=$BIGTABLE_TABLE \
  --bigtableColumnFamily=${BIGTABLE_COLUMN_FAMILY:-features} \
  --bigQueryTable=$BQ_TABLE \
  --enableEnrichment=${ENABLE_ENRICHMENT:-true} \
  --modelUri=$MODEL_URI"
