#!/usr/bin/env bash
#  Copyright 2026 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# Submits the gaming analytics streaming pipeline to Dataflow.
#
# Source the Terraform generated environment first:
#   source scripts/00_set_environment.sh

set -euo pipefail

for var in PROJECT REGION TEMP_LOCATION SERVICE_ACCOUNT INPUT_SUBSCRIPTION OUTPUT_TOPIC \
  ERROR_TOPIC BIGTABLE_INSTANCE BIGTABLE_TABLE BQ_TABLE; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: \$$var is not set. Run 'source scripts/00_set_environment.sh' first." >&2
    exit 1
  fi
done

# The Dataflow workers must never get a public IP, so they need a subnet with
# Private Google Access. SUBNETWORK is the current variable; NETWORK is kept as
# a fallback for environments generated by older versions of the Terraform code.
SUBNET_OPT=""
if [ -n "${SUBNETWORK:-}" ]; then
  SUBNET_OPT="--subnetwork=${SUBNETWORK}"
elif [ -n "${NETWORK:-}" ]; then
  SUBNET_OPT="--subnetwork=${NETWORK}"
fi

# WORKER_MACHINE_TYPE overrides the machine type exported by Terraform. The
# recommender shipped with this guide is CPU only, so there is no need for the
# GPU machine type that inference_mode="gpu" selects.
MACHINE_TYPE_OPT=""
EFFECTIVE_MACHINE_TYPE="${WORKER_MACHINE_TYPE:-${MACHINE_TYPE:-}}"
if [ -n "${EFFECTIVE_MACHINE_TYPE}" ]; then
  MACHINE_TYPE_OPT="--workerMachineType=${EFFECTIVE_MACHINE_TYPE}"
fi

DISK_OPT=""
if [ -n "${DISK_SIZE_GB:-}" ]; then
  DISK_OPT="--diskSizeGb=${DISK_SIZE_GB}"
fi

MAX_WORKERS_OPT=""
if [ -n "${MAX_DATAFLOW_WORKERS:-}" ]; then
  MAX_WORKERS_OPT="--maxNumWorkers=${MAX_DATAFLOW_WORKERS}"
fi

# GPU accelerators are only attached when explicitly requested: a Java pipeline
# running the bundled recommender does not use them, and requesting them
# consumes GPU quota for nothing.
ACCELERATOR_ARG=""
if [ "${USE_GPU_ACCELERATOR:-false}" = "true" ] && [ -n "${ACCELERATOR_OPT:-}" ]; then
  ACCELERATOR_ARG="--dataflowServiceOptions=${ACCELERATOR_OPT}"
fi

# INFERENCE_MODE comes from Terraform as either "gpu" (model on the workers) or
# "vertex" (model behind a Vertex AI endpoint).
INFERENCE_MODE_ARG="--inferenceMode=${INFERENCE_MODE:-local}"
ENDPOINT_ARG=""
if [ "${INFERENCE_MODE:-local}" = "vertex" ]; then
  if [ -z "${MODEL_ENDPOINT:-}" ]; then
    echo "ERROR: INFERENCE_MODE=vertex requires MODEL_ENDPOINT to be exported, as" >&2
    echo "       projects/PROJECT/locations/LOCATION/endpoints/ENDPOINT" >&2
    exit 1
  fi
  ENDPOINT_ARG="--modelEndpoint=${MODEL_ENDPOINT}"
fi

./gradlew run -Pargs="
  --runner=DataflowRunner \
  --project=$PROJECT \
  --region=$REGION \
  --tempLocation=$TEMP_LOCATION \
  --serviceAccount=$SERVICE_ACCOUNT \
  $SUBNET_OPT \
  $MACHINE_TYPE_OPT \
  $DISK_OPT \
  $MAX_WORKERS_OPT \
  $ACCELERATOR_ARG \
  --streaming \
  --enableStreamingEngine \
  --usePublicIps=false \
  --inputSubscription=$INPUT_SUBSCRIPTION \
  --outputTopic=$OUTPUT_TOPIC \
  --errorTopic=$ERROR_TOPIC \
  --bigtableInstance=$BIGTABLE_INSTANCE \
  --bigtableTable=$BIGTABLE_TABLE \
  --bigtableColumnFamily=${BIGTABLE_COLUMN_FAMILY:-features} \
  --bigQueryTable=$BQ_TABLE \
  --enableEnrichment=${ENABLE_ENRICHMENT:-true} \
  $INFERENCE_MODE_ARG \
  $ENDPOINT_ARG"
