#!/usr/bin/env bash
#  Copyright 2026 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# Submits the gaming analytics streaming pipeline to Dataflow.
#
# Run these first:
#   source scripts/00_set_environment.sh
#   ./scripts/01_build_and_push_container.sh
#   ./scripts/02_populate_bigtable.sh

set -euo pipefail

for var in PROJECT REGION TEMP_LOCATION SERVICE_ACCOUNT INPUT_SUBSCRIPTION OUTPUT_TOPIC \
  ERROR_TOPIC BIGTABLE_INSTANCE BIGTABLE_TABLE BQ_TABLE CONTAINER_URI; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: \$$var is not set. Run 'source scripts/00_set_environment.sh' first." >&2
    exit 1
  fi
done

# Where the model lives *inside* the harness container built by
# 01_build_and_push_container.sh. The Python SDK harness reads the pickle from
# this local path, so there is no per-worker download.
#
# Advanced use: point this at a gs:// URI and drop the container override below
# to have the harness fetch the model from Cloud Storage instead. The stock
# harness image then has to be pulled from Docker Hub, which needs egress.
MODEL_PATH="${MODEL_PATH:-/opt/gaming_analytics/recommender.pkl}"

# The Dataflow workers must never get a public IP, so they need a subnet with
# Private Google Access. SUBNETWORK is the current variable; NETWORK is kept as
# a fallback for environments generated by older versions of the Terraform code.
SUBNET_OPT=""
if [ -n "${SUBNETWORK:-}" ]; then
  SUBNET_OPT="--subnetwork=${SUBNETWORK}"
elif [ -n "${NETWORK:-}" ]; then
  SUBNET_OPT="--subnetwork=${NETWORK}"
fi

# WORKER_MACHINE_TYPE overrides the machine type exported by Terraform. The
# model runs on the worker CPU, in the Python SDK harness, so a GPU machine type
# would buy nothing; note that Runner v2 multi-language jobs run a Java and a
# Python harness side by side, so give the workers enough memory.
MACHINE_TYPE_OPT=""
EFFECTIVE_MACHINE_TYPE="${WORKER_MACHINE_TYPE:-${MACHINE_TYPE:-}}"
if [ -n "${EFFECTIVE_MACHINE_TYPE}" ]; then
  MACHINE_TYPE_OPT="--workerMachineType=${EFFECTIVE_MACHINE_TYPE}"
fi

DISK_OPT=""
if [ -n "${DISK_SIZE_GB:-}" ]; then
  DISK_OPT="--diskSizeGb=${DISK_SIZE_GB}"
fi

MAX_WORKERS_OPT=""
if [ -n "${MAX_DATAFLOW_WORKERS:-}" ]; then
  MAX_WORKERS_OPT="--maxNumWorkers=${MAX_DATAFLOW_WORKERS}"
fi

# Replaces the Python SDK harness that the expansion service asks for (by
# default apache/beam_python3.13_sdk:2.76.0, pulled from Docker Hub) with our
# Artifact Registry image, which already contains the model and its pinned
# dependencies. The Java harness is left alone; only the Python one matches the
# regex. No quotes and no spaces: build.gradle splits these args on whitespace.
HARNESS_OVERRIDE_OPT="--sdkHarnessContainerImageOverrides=.*python.*,${CONTAINER_URI}"

echo "Submitting the gaming analytics pipeline to Dataflow."
echo "  project        : ${PROJECT} (${REGION})"
echo "  input          : ${INPUT_SUBSCRIPTION}"
echo "  recommendations: ${OUTPUT_TOPIC}"
echo "  dead letter    : ${ERROR_TOPIC}"
echo "  harness image  : ${CONTAINER_URI}"
echo "  model path     : ${MODEL_PATH}"
echo

./gradlew run -Pargs="
  --runner=DataflowRunner \
  --project=$PROJECT \
  --region=$REGION \
  --tempLocation=$TEMP_LOCATION \
  --serviceAccount=$SERVICE_ACCOUNT \
  $SUBNET_OPT \
  $MACHINE_TYPE_OPT \
  $DISK_OPT \
  $MAX_WORKERS_OPT \
  --streaming \
  --enableStreamingEngine \
  --experiments=use_runner_v2 \
  $HARNESS_OVERRIDE_OPT \
  --usePublicIps=false \
  --inputSubscription=$INPUT_SUBSCRIPTION \
  --outputTopic=$OUTPUT_TOPIC \
  --errorTopic=$ERROR_TOPIC \
  --bigtableInstance=$BIGTABLE_INSTANCE \
  --bigtableTable=$BIGTABLE_TABLE \
  --bigtableColumnFamily=${BIGTABLE_COLUMN_FAMILY:-features} \
  --bigQueryTable=$BQ_TABLE \
  --enableEnrichment=${ENABLE_ENRICHMENT:-true} \
  --modelUri=$MODEL_PATH"

echo
echo "Next: ./scripts/04_publish_events.sh"
