# This file is generated by the Terraform code of this Solution Guide.
# We recommend that you modify this file only through the Terraform deployment.
export PROJECT=malhotradi
export REGION=us-central1
export SUBNETWORK=regions/us-central1/subnetworks/dataflow-subnet
export TEMP_LOCATION=gs://$PROJECT/tmp
export SERVICE_ACCOUNT=my-dataflow-sa@malhotradi.iam.gserviceaccount.com

export DOCKER_REPOSITORY=dataflow-containers
export IMAGE_NAME=dataflow-solutions-cdp
export DOCKER_TAG=0.1
export DOCKER_IMAGE=$REGION-docker.pkg.dev/$PROJECT/$DOCKER_REPOSITORY/$IMAGE_NAME

export CONTAINER_URI=$DOCKER_IMAGE:$DOCKER_TAG

export MAX_DATAFLOW_WORKERS=1
export DISK_SIZE_GB=200
export MACHINE_TYPE=e2-standard-8

export BQ_DATASET=output_dataset
export BQ_CDP_DATASET="cdp"
export GCS_BUCKET=gs://$PROJECT/assets/dataflow-solution-guide-cdp
