#  Copyright 2025 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

locals {
  bucket_name              = var.bucket_name != null ? var.bucket_name : var.project_id
  dataflow_service_account = var.service_account_name != null ? var.service_account_name : "marketing-intel-sa"
  max_dataflow_workers     = 1
  worker_disk_size_gb      = 200
  machine_type             = "n2-standard-4"
  bigquery_dataset         = "output_dataset"
  bigquery_table           = "predictions"
  firestore_collection     = "customer_profiles"
}

data "google_project" "project" {
  project_id = var.project_id
}

// Artifact Registry repository for custom Dataflow worker containers
module "registry_docker" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/artifact-registry?ref=v57.0.0"
  project_id = var.project_id
  location   = var.region
  name       = "dataflow-containers"
  format     = { docker = { standard = {} } }
  iam = {
    "roles/artifactregistry.admin" = [
      "serviceAccount:${data.google_project.project.number}@cloudbuild.gserviceaccount.com",
      "serviceAccount:${data.google_project.project.number}-compute@developer.gserviceaccount.com"
    ]
    "roles/artifactregistry.reader" = [
      module.dataflow_sa.iam_email
    ]
  }
  cleanup_policy_dry_run = false
  cleanup_policies = {
    keep-3-versions = {
      action = "KEEP"
      most_recent_versions = {
        keep_count = 3
      }
    }
  }
}

// Optional GCS Bucket for staging data and scripts
module "buckets" {
  count         = var.create_bucket ? 1 : 0
  source        = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/gcs?ref=v57.0.0"
  project_id    = var.project_id
  name          = local.bucket_name
  location      = var.region
  storage_class = "STANDARD"
  force_destroy = var.destroy_all_resources
}

// Pub/Sub input topic and subscription
module "input_topic" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/pubsub?ref=v57.0.0"
  project_id = var.project_id
  name       = "dataflow-solutions-guide-market-intelligence-input"
  subscriptions = {
    dataflow-solutions-guide-market-intelligence-input-sub = {}
  }
}

// Pub/Sub output topic and subscription for real-time coupon/discount activations
module "output_topic" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/pubsub?ref=v57.0.0"
  project_id = var.project_id
  name       = "dataflow-solutions-guide-market-intelligence-output"
  subscriptions = {
    dataflow-solutions-guide-market-intelligence-output-sub = {}
  }
}

// Enable Cloud Firestore API
resource "google_project_service" "firestore" {
  project            = var.project_id
  service            = "firestore.googleapis.com"
  disable_on_destroy = false
}

// Cloud Firestore (Native Mode) for real-time customer profile lookups
resource "google_firestore_database" "database" {
  project         = var.project_id
  name            = "(default)"
  location_id     = var.region
  type            = "FIRESTORE_NATIVE"
  deletion_policy = var.destroy_all_resources ? "DELETE" : "ABANDON"

  depends_on = [
    google_project_service.firestore
  ]
}

// BigQuery dataset for prediction persistence
module "output_dataset" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/bigquery-dataset?ref=v57.0.0"
  project_id = var.project_id
  id         = local.bigquery_dataset
  location   = var.region
  access = {
    dataflow-writer = { role = "OWNER", type = "user" }
  }
  access_identities = {
    dataflow-writer = module.dataflow_sa.email
  }
  options = {
    delete_contents_on_destroy = var.destroy_all_resources
  }
}

// Dedicated Dataflow Worker Service Account
module "dataflow_sa" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/iam-service-account?ref=v57.0.0"
  project_id = var.project_id
  name       = local.dataflow_service_account
  iam_project_roles = {
    (var.project_id) = [
      "roles/storage.objectAdmin",
      "roles/dataflow.worker",
      "roles/monitoring.metricWriter",
      "roles/pubsub.editor",
      "roles/datastore.user",
      "roles/bigquery.dataEditor"
    ]
  }
}

// Script with variables to launch the Dataflow jobs
resource "local_file" "variables_script" {
  filename        = "${path.module}/../../pipelines/marketing_intelligence/scripts/00_set_variables.sh"
  file_permission = "0644"
  content         = <<FILE
# This file is generated by the Terraform code of this Solution Guide.
# We recommend that you modify this file only through the Terraform deployment.
export PROJECT=${var.project_id}
export REGION=${var.region}
export SUBNETWORK=${var.subnetwork != null ? var.subnetwork : ""}
export NETWORK=$${SUBNETWORK}
export TEMP_LOCATION=gs://${local.bucket_name}/tmp
export SERVICE_ACCOUNT=${module.dataflow_sa.email}

export DOCKER_REPOSITORY=${module.registry_docker.name}
export IMAGE_NAME=dataflow-solutions-market-intelligence
export DOCKER_TAG=0.1
export DOCKER_IMAGE=$REGION-docker.pkg.dev/$PROJECT/$DOCKER_REPOSITORY/$IMAGE_NAME

export CONTAINER_URI=$DOCKER_IMAGE:$DOCKER_TAG

export MAX_DATAFLOW_WORKERS=${local.max_dataflow_workers}
export DISK_SIZE_GB=${local.worker_disk_size_gb}
export MACHINE_TYPE=${local.machine_type}

export FIRESTORE_COLLECTION=${local.firestore_collection}
export BQ_DATASET=${module.output_dataset.dataset_id}
export BQ_TABLE=${local.bigquery_table}
export INPUT_TOPIC=projects/${var.project_id}/topics/dataflow-solutions-guide-market-intelligence-input
export INPUT_SUBSCRIPTION=projects/${var.project_id}/subscriptions/dataflow-solutions-guide-market-intelligence-input-sub
export OUTPUT_TOPIC=projects/${var.project_id}/topics/dataflow-solutions-guide-market-intelligence-output
export OUTPUT_SUBSCRIPTION=projects/${var.project_id}/subscriptions/dataflow-solutions-guide-market-intelligence-output-sub
FILE
}
