#  Copyright 2025 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

locals {
  spanner_instance         = "test-spanner-instance"
  spanner_database         = "taxis_database"
  spanner_table            = "events"
  spanner_change_stream    = "events_stream"
  spanner_metadata_db      = "metadata"
  spanner_configuration    = "regional-${var.region}"
  spanner_name             = "Spanner instance managed by TF"
  bigquery_dataset         = "replica"
  dataflow_service_account = var.service_account_name != null ? var.service_account_name : "spanner-cdc-dataflow-sa"
  worker_type              = "n2-standard-4"
  max_dataflow_workers     = 10
  bucket_name              = var.bucket_name != null ? var.bucket_name : var.project_id
}

// Service account for Dataflow workers
module "dataflow_sa" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/iam-service-account?ref=v57.0.0"
  project_id = var.project_id
  name       = local.dataflow_service_account
  iam_project_roles = {
    (var.project_id) = [
      "roles/storage.objectAdmin",
      "roles/dataflow.worker",
      "roles/monitoring.metricWriter",
      "roles/pubsub.editor",
      "roles/bigquery.dataEditor",
      "roles/bigquery.jobUser"
    ]
  }
}

// Optional GCS Bucket for staging & temp location
module "buckets" {
  count         = var.create_bucket ? 1 : 0
  source        = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/gcs?ref=v57.0.0"
  project_id    = var.project_id
  name          = local.bucket_name
  location      = var.region
  storage_class = "STANDARD"
  force_destroy = var.destroy_all_resources
}

// BigQuery dataset for final destination
module "dataset" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/bigquery-dataset?ref=v57.0.0"
  project_id = var.project_id
  id         = local.bigquery_dataset
  location   = var.region
  access = {
    dataflow-writer = { role = "OWNER", type = "user" }
  }
  access_identities = {
    dataflow-writer = module.dataflow_sa.email
  }

  options = {
    delete_contents_on_destroy = var.destroy_all_resources
  }
}

// Spanner instance for change streams / CDC, using minimal instances size for demo purposes
resource "google_spanner_instance" "spanner_instance" {
  config           = local.spanner_configuration
  name             = local.spanner_instance
  project          = var.project_id
  display_name     = local.spanner_name
  processing_units = 1000
  force_destroy    = var.destroy_all_resources
}

resource "google_spanner_database" "taxis" {
  instance = google_spanner_instance.spanner_instance.name
  project  = var.project_id
  name     = local.spanner_database
  ddl = [
    <<DDL1
CREATE TABLE ${local.spanner_table} (
  ride_id STRING(64),
  point_idx INT64,
  latitude FLOAT64,
  longitude FLOAT64,
  timestamp TIMESTAMP,
  meter_reading FLOAT64,
  meter_increment FLOAT64,
  ride_status STRING(64),
  passenger_count INT64,
) PRIMARY KEY(ride_id, point_idx)
DDL1
    ,
    <<DDL2
CREATE CHANGE STREAM ${local.spanner_change_stream} FOR ${local.spanner_table}
OPTIONS(value_capture_type = 'NEW_ROW_AND_OLD_VALUES')
DDL2
  ]
  deletion_protection = !var.destroy_all_resources
}

resource "google_spanner_database_iam_binding" "read_write_taxis" {
  project  = var.project_id
  instance = google_spanner_instance.spanner_instance.name
  database = google_spanner_database.taxis.name
  role     = "roles/spanner.databaseUser"
  members = [
    module.dataflow_sa.iam_email
  ]
}

resource "google_spanner_database" "metadata" {
  instance            = google_spanner_instance.spanner_instance.name
  project             = var.project_id
  name                = local.spanner_metadata_db
  deletion_protection = !var.destroy_all_resources
}

resource "google_spanner_database_iam_binding" "read_write_metadata" {
  project  = var.project_id
  instance = google_spanner_instance.spanner_instance.name
  database = google_spanner_database.metadata.name
  role     = "roles/spanner.databaseUser"
  members = [
    module.dataflow_sa.iam_email
  ]
}

// Script with variables to launch the Dataflow jobs
resource "local_file" "variables_script" {
  filename        = "${path.module}/../../pipelines/etl_integration_java/scripts/01_set_variables.sh"
  file_permission = "0644"
  content         = <<FILE
# This file is generated by the Terraform code of this Solution Guide.
# We recommend that you modify this file only through the Terraform deployment.
export PROJECT=${var.project_id}
export REGION=${var.region}
export SUBNETWORK=${var.subnetwork != null ? var.subnetwork : ""}
export NETWORK=$${SUBNETWORK}
export TEMP_LOCATION=gs://${local.bucket_name}/tmp
export SERVICE_ACCOUNT=${module.dataflow_sa.email}

export TOPIC=projects/pubsub-public-data/topics/taxirides-realtime
export SPANNER_INSTANCE=${google_spanner_instance.spanner_instance.name}
export SPANNER_DATABASE=${local.spanner_database}
export SPANNER_METADATA_DB=${local.spanner_metadata_db}
export SPANNER_TABLE=${local.spanner_table}
export SPANNER_CHANGE_STREAM=${local.spanner_change_stream}

export BIGQUERY_DATASET=${local.bigquery_dataset}

export MAX_DATAFLOW_WORKERS=${local.max_dataflow_workers}
export WORKER_TYPE=${local.worker_type}
FILE
}

