export PROJECT_ID=learnings-421714
export INSTANCE_ID=iot-analytics
export TABLE_ID=maintenance_data
export VEHICLE_DATA_PATH=/Users/paraschavda/GCloud/data_sol_guides/dataflow_solution_guides/pipelines/iot_analytics/scripts/vehicle_data.jsonl
export MAINTENANCE_DATA_PATH=/Users/paraschavda/GCloud/data_sol_guides/dataflow_solution_guides/pipelines/iot_analytics/scripts/maintenance_data.jsonl
export PUBSUB_TOPIC_ID=maintenance-data