name: 'Terraform static validation'
on:
  pull_request:
permissions:
  contents: read
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: "Terraform:\n  - 'terraform/**'     \n"
      - name: 'Google Cloud auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: '${{ secrets.TESTING_PROJECT }}'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
